openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /api/Employees/GetAllEmployees:
    get:
      summary: Retrieve all employees
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '404':
          description: No employees found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse' # Define ErrorResponse schema if necessary

components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: The employee ID
        empName:
          type: string
          nullable: true
          description: The employee name
        password:
          type: string
          nullable: true
          description: The employee password
